
title = "Open IoE Document"
languageCode = "en-us"


baseURL = "http:localhost:1313/"


# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

enableInlineShortcodes= true


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
	  hrefTargetBlank = true

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "matlab"
name = "Matlab"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Version: 2.0</a>",
"Documentation Powered by [OpenIoE](https://openioe.in)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[module]
[module.hugoVersion]
min = "0.56.0"
[[module.imports]]
path="github.com/jquery/jquery-dist"
[[module.imports.mounts]]
source="dist/jquery.js"
target="assets/js/slate/lib/_jquery.js"
[[module.imports]]
path="github.com/olivernn/lunr.js"
[[module.imports.mounts]]
source="lunr.js"
target="assets/js/slate/lib/_lunr.js"
[[module.imports]]
path="github.com/slatedocs/slate"
[[module.imports.mounts]]
source="source/images"
target="static/images"
[[module.imports.mounts]]
source="source/fonts"
target="static/fonts"
[[module.imports.mounts]]
source="source/stylesheets"
target="assets/scss/slate"
[[module.imports.mounts]]
source="source/javascripts"
target="assets/js/slate"
